### ISSUE TITLE
Count the words and letters in text

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#1]
Count the number of words or letters or both in the text that the user provides and show it on the result page below the text result.

**Comment by Amit366** [comment]
Can I work on this issue??

**Comment by rockingrohit9639** [comment]
> Can I work on this issue??

Yeah sure.

**Comment by rockingrohit9639** [comment]
> Can I work on this issue??

I have assigned you this task. You can do it in 4 days. Is it ok for you?

**Comment by Amit366** [comment]
Yes sir

**Comment by rockingrohit9639** [comment]
> Yes sir

Bro is fine ❤️
