### ISSUE TITLE
Add feature to search email.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#10]
Add a feature to find or search emails in a given long text.
* Hint - You can use Regular Expressions

**Comment by Sloth-Panda** [comment]
would like to work on this

**Comment by rockingrohit9639** [comment]
> would like to work on this

Bro, I would suggest you to complete issue > #2 . These both are related to each other. So, if you complete it first. Your half work will be done.

**Comment by rockingrohit9639** [comment]
> would like to work on this

@Sloth-Panda you can work on it.

**Comment by arbazalam01** [comment]
Can you assign this issue to me

**Comment by rockingrohit9639** [comment]
> Can you assign this issue to me

Yes @arbazalam01, you can work on it. 
I am assigning you this issue.

### You are given 6 days to complete it as you are also on another issue.
