### ISSUE TITLE
Add contact us below services.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#101]
## 💥 Proposal

Add the contact us section (form) below the services section. 
The section should match the theme of our website i.e. black and white.

Form Fields 
- Full Name
- Email Address
- Message

**Comment by pranabprohit** [comment]
Hii @rockingrohit9639, I would like to work on this issue.

**Comment by rockingrohit9639** [comment]
> Hii @rockingrohit9639, I would like to work on this issue.

Ok @pranabprohit bro, You can work on it.

### You are given 4 days to complete it.
