### ISSUE TITLE
Add some animations on website.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#102]
## 💥 Proposal

Add some animations on the website.
Hints -
- You can add some shapes and animate them.
- You can animate TextAnalyzer text on the navigation bar.
- You can animate T. letter on the homepage by resizing it.

Use your imagination and do whatever you want.

**Comment by pri1311** [comment]
Would like to work on this too.

**Comment by rockingrohit9639** [comment]
> Would like to work on this too.

Ok @pri1311, I will assign you this one after completing others

**Comment by rockingrohit9639** [comment]
> Would like to work on this too.

Hey @pri1311, you can work on this issue now.
I am assigning you this one.
### Make sure you complete it in 5days.

**Comment by rockingrohit9639** [comment]
@pri1311 are you working on it?

**Comment by pri1311** [comment]
Hey! Yes I am. Can I get a little more time though?

**Comment by rockingrohit9639** [comment]
> Hey! Yes I am. Can I get a little more time though?

Ok @pri1311, No problem. Are 3 days more enough?

**Comment by pri1311** [comment]
Yes. Thank you so much

**Comment by rockingrohit9639** [comment]
> Yes. Thank you so much

Ok, Your welcome.
