### ISSUE TITLE
Add a back button on youtube.html

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#105]
## 💥 Proposal

Add a back button on the youtube.html file.
Make sure it navigates to generate page i.e. /index2

**Comment by pri1311** [comment]
please assign this to me under crooswoc.

**Comment by rockingrohit9639** [comment]
> please assign this to me under crooswoc.

Ok @pri1311, you can work on it.

### You are given 2 days to complete it.

**Comment by rockingrohit9639** [comment]
> > please assign this to me under crooswoc.
> 
> Ok @pri1311, you can work on it.
> 
> ### You are given 2 days to complete it.

@pri1311, can you send me a message on discord?

**Comment by pri1311** [comment]
Sure

**Comment by pri1311** [comment]
It shows invalid invite

**Comment by rockingrohit9639** [comment]
> It shows invalid invite

I have updated the link. Can you please try again?

**Comment by pri1311** [comment]
Still facing the same issue.

**Comment by rockingrohit9639** [comment]
> Still facing the same issue.

Try joining using this link - https://discord.gg/pNcPUNC6
