### ISSUE TITLE
Connect ContactUs form with backend.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#108]
## 💥 Proposal

Connect ContactUs form with the backend i.e. store the data entered in form in the database.
Database should be SQLite(already existing).

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by rockingrohit9639** [comment]
> can i work on this issue

You can work on this issue @arbazalam01.

### You are given 6 days to complete it.
