### ISSUE TITLE
Would like to add code of conduct and contributing file

### ISSUE THREAD

**Issue by Sloth-Panda** [rockingrohit9639/TextAnalyzer#11]
@rockingrohit9639 as these are important  and should be sperate files for better clarity would like to  make those as part of cwoc

**Comment by rockingrohit9639** [comment]
Good idea. It should be there in repo.
Will you do it too, should I give chance to anyone else?

**Comment by Sloth-Panda** [comment]
I would love to contribute to it, I have been already assigned one but I will be sending both the prs tomorrow only so you can assign me

**Comment by rockingrohit9639** [comment]
> I would love to contribute to it, I have been already assigned one but I will be sending both the prs tomorrow only so you can assign me

Ok bro, I have assigned you.

**Comment by rockingrohit9639** [comment]
Thank you @Sloth-Panda . I am closing this issue.
