### ISSUE TITLE
Add default text 

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#112]
## 💥 Proposal

The idea is to add a default text button in which when a user select a radio button then on pressing this button, it gives default text for that feature. Also a clear button to clear the text in text area. (Both for analysis and generate page) 

Example : 
User press the remove punctuation radio button 

then default text button gives a random text to check this feature. 
Like =text!!analysis 

It will show this text on text area. 

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by Akash20x** [comment]
I want to solve this issue when you accept this issue

**Comment by rockingrohit9639** [comment]
> ## 💥 Proposal
> The idea is to add a default text button in which when a user select a radio button then on pressing this button, it gives default text for that feature. Also a clear button to clear the text in text area. (Both for analysis and generate page)
> 
> Example :
> User press the remove punctuation radio button
> 
> then default text button gives a random text to check this feature.
> Like =text!!analysis
> 
> It will show this text on text area.
> 
> ### Have you read the _Contributing Guidelines on Pull Requests_ ?
> Yes

Ok @Akash20x. I got it. You can work on it.

### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
Please add necessary labels to this issue

**Comment by rockingrohit9639** [comment]
Will you add both clear and default text?

**Comment by Akash20x** [comment]
> Will you add both clear and default text?

Yes

**Comment by rockingrohit9639** [comment]
Ok.

**Comment by Akash20x** [comment]
Please check my pull request
