### ISSUE TITLE
Provide links for latest articles 

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#114]
## 💥 Proposal

It will provide links for the medium articles which are published (today) according to genre 

It will give article link, title, writer and publisher name. 

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

You can work on it @Akash20x 

### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
This issue will take too much time to solve and less days for crosswoc to end, so I withdraw from this issue.

So I will close this issue.

**Comment by Akash20x** [comment]
Please help me regarding this issue, Check my DM on discord

**Comment by Akash20x** [comment]
Please check my pull request
