### ISSUE TITLE
Add confirmation message

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#117]
## 💥 Proposal

Add a confirmation message when someone submits the contact us form.

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by pranabprohit** [comment]
Hii @rockingrohit9639, I would like to work on this issue. can you please assign me this issue.

**Comment by rockingrohit9639** [comment]
> Hii @rockingrohit9639, I would like to work on this issue. can you please assign me this issue.

Yes @pranabprohit, You can work on it.

### Make sure you complete it in 4 days.
