### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [rockingrohit9639/TextAnalyzer#12]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

**Comment by muthuannamalai12** [comment]
I would like to work on it as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> I would like to work on it as a part of Cross Woc

I am assigning you this one. Make sure you read README.md file and How to Contribute.
I will be giving you 4-5 days to do this. Is it ok foor you?

**Comment by muthuannamalai12** [comment]
> > I would like to work on it as a part of Cross Woc
> 
> I am assigning you this one. Make sure you read README.md file and How to Contribute.
> I will be giving you 4-5 days to do this. Is it ok foor you?

It is ok for me bro

**Comment by rockingrohit9639** [comment]
Thank you @muthuannamalai12 
PR > #18
