### ISSUE TITLE
Lemmatizer option in text analysis 

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#120]
## 💥 Proposal

Add the feature to do lemmatization of the text. 

First it search if there is need of lemmatization or not,if required, then it find all words in their lemmatization form and display it on analysis page. 

Example 1:
Go to this link 
Output : No need of lemmatization 

Example 2:
Your text is ready to be analysed 
Output : 
(Original word) - > (Lemmatized word) 
is - > be 
analysed - >analyse 

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by Akash20x** [comment]
If consider this issue, please assign me this issue as a part of Cross

**Comment by rockingrohit9639** [comment]
> If consider this issue, please assign me this issue as a part of CrossWoc

Ok @Akash20x, You can start working on this.

### Make sure you complete it in 5 days.

**Comment by Akash20x** [comment]
Please check my pull request
