### ISSUE TITLE
Add alert pop-up for contact form fields.

### ISSUE THREAD

**Issue by pranabprohit** [rockingrohit9639/TextAnalyzer#122]
If the person did not fill the form properly like any field is not filled or mail id provided is not proper a alert message will pop up with a message that this or that is not filled or not proper.

**Comment by pranabprohit** [comment]
Hii @rockingrohit9639 , I would like to work on this issue as a part of CWOC. can you please assign me this issue.

**Comment by rockingrohit9639** [comment]
> Hii @rockingrohit9639 , I would like to work on this issue as a part of CWOC. can you please assign me this issue.

Ok @pranabprohit You can work on it.

### You are given 5 days to complete it.
