### ISSUE TITLE
Generate pdf for textarea text 

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#123]
## 💥 Proposal

Add an option Pdf Viewer that will create a pdf viewer html page for the text given by user in the textarea. User can also download this pdf. 

This feature is useful when user analyse a long text and paste analysed text into textarea and now it will create its pdf. 

For example : 

We used a uppercase for our long text and now we have large text in uppercase, now it will create its pdf and share it in pdf form 

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

Anyone can work on it

**Comment by rockingrohit9639** [comment]
> ## 💥 Proposal
> Add an option Pdf Viewer that will create a pdf viewer html page for the text given by user in the textarea. User can also download this pdf.
> 
> This feature is useful when user analyse a long text and paste analysed text into textarea and now it will create its pdf.
> 
> For example :
> 
> We used a uppercase for our long text and now we have large text in uppercase, now it will create its pdf and share it in pdf form
> 
> ### Have you read the _Contributing Guidelines on Pull Requests_ ?
> Yes
> 
> Anyone can work on it

Ok @Akash20x, I will assign you this issue once you finishes the old one.

**Comment by Akash20x** [comment]
Please assign me this issue

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by rockingrohit9639** [comment]
> Please check my pull request

Bro, I will review and merge your PR tomorrow.

**Comment by Akash20x** [comment]
OK, no problem
