### ISSUE TITLE
Extract text from pdf

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#125]
## 💥 Proposal

Add a feature to upload a pdf file only and then extract the text from it and show it on the result page.

### Have you read the *Contributing Guidelines on Pull Requests*?

Yes

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by rockingrohit9639** [comment]
> can i work on this issue

@arbazalam01 You can work on it.

### Make sure you complete it in 6days.

**Comment by rockingrohit9639** [comment]
@arbazalam01 bro, Today is the last day.
