### ISSUE TITLE
two spelling errors

### ISSUE THREAD

**Issue by pri1311** [rockingrohit9639/TextAnalyzer#126]
## 💥 Proposal

On the cards, spelling should be 'entering'

### Have you read the *Contributing Guidelines on Pull Requests* ?
yes

**Comment by rockingrohit9639** [comment]
> ## 💥 Proposal
> On the cards, spelling should be 'entering'
> 
> ### Have you read the _Contributing Guidelines on Pull Requests_ ?
> yes

ok @pri1311, you can fix this, and yeah please check if there are any other spelling errors. Thank you.
