### ISSUE TITLE
Prevent empty text to be analyzed

### ISSUE THREAD

**Issue by pri1311** [rockingrohit9639/TextAnalyzer#127]
## 💥 Proposal

even if no text is entered, app goes to the result page, this should probably be avoided and user should be prompted to enter some text first

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by rockingrohit9639** [comment]
> ## 💥 Proposal
> even if no text is entered, app goes to the result page, this should probably be avoided and user should be prompted to enter some text first
> 
> ### Have you read the _Contributing Guidelines on Pull Requests_ ?
> Yes

Hmmm, Thank would be better. If you can do it then let me know I will assign you this issue.

**Comment by rockingrohit9639** [comment]
@pri1311 will you do it?

**Comment by pri1311** [comment]
As I mentioned not very acquainted with django, would need help if do it :(

**Comment by rockingrohit9639** [comment]
> As I mentioned not very acquainted with django, would need help if do it :(

Ok I can help you if you want.

**Comment by pri1311** [comment]
okay will do it then, thank you
