### ISSUE TITLE
Replace + Word cloud for text analysis

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#129]
## 💥 Proposal

I want to add 2 features : 
1. Add a replace option to replace text in text area with a word and show it on analyse page. 
2. Add a word cloud for the text given in text area and show it in generate page. 

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
@Akash20x, You can start working on it.

### You are given 5 days to complete it.

**Comment by Akash20x** [comment]
Please check my pull request
