### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#13]
Add screenshots in README.md file.
Screenshots are already there in the repo, you just have to include them in the README file by keeping the heading Screenshots.
Name of files :- 
- ss1.png
- ss2.png

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross Woc. Kindly Assign me

**Comment by rockingrohit9639** [comment]
> I would love to work on this issue as a part of Cross Woc. Kindly Assign me

Bro, I have already assigned you two issues already. I think we should give chance to anyone else. If no one asks for assigning this, I will assign it to you? Is it ok for you?

**Comment by muthuannamalai12** [comment]
> > I would love to work on this issue as a part of Cross Woc. Kindly Assign me
> 
> Bro, I have already assigned you two issues already. I think we should give chance to anyone else. If no one asks for assigning this, I will assign it to you? Is it ok for you?

Ok Bro

**Comment by tharunc** [comment]
I would like to work on this Issue as a part of **CWOC**.
Kindly assign me this issue. 

                    THANK YOU

**Comment by rockingrohit9639** [comment]
> NK YOU

Yeah, sure. Are 2-3 days fine for completing it?

**Comment by tharunc** [comment]
Yes

**Comment by rockingrohit9639** [comment]
Thank you @tharunc 
PR > #23
