### ISSUE TITLE
Date Extractor + Word Frequency Bar Graph 

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#132]
## 💥 Proposal

Add an option to extract dates from text and shown it in analyse page. Also a option of word frequencies which display a bar graph of word frequencies of top ten words in text in analyze page. 

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

Ok @Akash20x  you can start working on it.

**Comment by Akash20x** [comment]
OK
