### ISSUE TITLE
Create separate file for How to Contribute

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#14]
Create a separate file for How to contribute. Code for how to contribute is already written in README file, cut it from there and paste it in How to contribute file.

**Comment by muthuannamalai12** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by Sloth-Panda** [comment]
issue and pr has already been made 

issue -> #11 , pr-> #15 

your issue means contributing file here. THANK YOU!

**Comment by rockingrohit9639** [comment]
Hii @muthuannamalai12 Just a quick message. Half of the work is already done by @Sloth-Panda 
So now you just have to remove the How to Contribute part from the README.md file. 
Sorry for the inconvenience.

**Comment by muthuannamalai12** [comment]
> Hii @muthuannamalai12 Just a quick message. Half of the work is already done by @Sloth-Panda
> So now you just have to remove the How to Contribute part from the README.md file.
> Sorry for the inconvenience.

Ok @rockingrohit9639. No Worries

**Comment by rockingrohit9639** [comment]
Issue solved by @muthuannamalai12 
PR #17

**Comment by rockingrohit9639** [comment]
Issue solved by @muthuannamalai12
PR #17
