### ISSUE TITLE
creation of issue and pr templates

### ISSUE THREAD

**Issue by Sloth-Panda** [rockingrohit9639/TextAnalyzer#16]
There are no issue and pr template that will describes what sort of issue is being raised (issue template) and the description of pr with its checklist(pr template). Let me know if this needs to be done as part of cwoc. Thank you!

**Comment by rockingrohit9639** [comment]
> There are no issue and pr template that will describes what sort of issue is being raised (issue template) and the description of pr with its checklist(pr template). Let me know if this needs to be done as part of cwoc. Thank you!

I am assigning you for this task.

**Comment by rockingrohit9639** [comment]
Thank you @Sloth-Panda 
PR - #20

**Comment by rockingrohit9639** [comment]
Thank you @Sloth-Panda
PR - #20
