### ISSUE TITLE
converting from . to new line

### ISSUE THREAD

**Issue by darklalit14** [rockingrohit9639/TextAnalyzer#19]
The dot(.) will be coverted into the new line,so that it will look good and easy to understand.
It is useful for making the points in the text.
* note- I am a beginner please help me in understanding he code.

**Comment by rockingrohit9639** [comment]
> The dot(.) will be coverted into the new line,so that it will look good and easy to understand.
> It is useful for making the points in the text.
> 
> * note- I am a beginner please help me in understanding he code.

It sounds good bro and don't worry just drop me a message on Discord, I will help you in understanding the code.
I am assigning you this task. As you are a beginner I will be giving you 3-4 days to solve this issue.

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by rockingrohit9639** [comment]
> Can i work on this issue

Yes @arbazalam01 , you can work on it. 
Make sure you read our CODE_OF_CONDUCT.
If you have any doubt you can reach me on our Discord Server.

### You are given 4 days to complete it.
