### ISSUE TITLE
Add find feature

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#2]
Add a feature that enables a user to find a word in the text.

**Comment by ayushrastogi689** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by rockingrohit9639** [comment]
> I want to work on this issue. Please assign me this issue.

Ok @ayushrastogi689 I am assigning you this issue. Make sure you complete it in 3-4 days.

**Comment by ayushrastogi689** [comment]
Sure.

**Comment by rockingrohit9639** [comment]
Thank you @ayushrastogi689
