### ISSUE TITLE
Clean the code

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#25]
## 💥 Proposal
Clean the code by removing the unnecessary comment in all the files.
Make sure you don't remove any line which is in use.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by rockingrohit9639** [comment]
Yes, you can work on it. Make sure you don't remove or change any line which is in use.
Also, try to understand which code section is doing what. The main aim of this issue is that you go through all the files and understand the code and workflow of Django.
## You are given 2 days to do it.

**Comment by Akash20x** [comment]
OK, I will do it

**Comment by rockingrohit9639** [comment]
> OK, I will do it

ok

**Comment by Akash20x** [comment]
Update : 
I started working on it and send pull request itself by today.

**Comment by rockingrohit9639** [comment]
> Update :
> I started working on it and send pull request itself by today.

Ok @Akash20x
