### ISSUE TITLE
Add AboutUs page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#3]
Add an AboutUs page so that anyone as a beginner can come and write his/her name on that page as a contributor and create his/her pull request and learn about it.

**Comment by Sloth-Panda** [comment]
Can I make this?

**Comment by rockingrohit9639** [comment]
> Can I make this? As part of cwoc?

Yes. Why not.

**Comment by rockingrohit9639** [comment]
> Can I make this? As part of cwoc?

Bro, I am assigning you this task. You have 4 days to complete it.

**Comment by Sloth-Panda** [comment]
can you give me a little bit of context on how it should look? Or I will do  it on my own way and will show it to you?

**Comment by rockingrohit9639** [comment]
> can you give me a little bit of context on how it should look? Or I will do it on my own way and will show it to you?

You can do it of your own, make it fancy filled with color, or just a simple about us page it is totally up to you. 
You are given 4 days to do this work, is it ok for you?

**Comment by rockingrohit9639** [comment]
@Sloth-Panda Bro, today is your last day to complete this work.
