### ISSUE TITLE
Addding contributors on AboutUs page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#31]
## 💥 Proposal

Add contributors on the About Us page using GitHub API.
- Use their avatars too
-  Do anything to look it better.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by Akash20x** [comment]
Can you tell me what you mean by avators

**Comment by rockingrohit9639** [comment]
> Can you tell me what you mean by avatars

Avatar means the GitHub profile photos of contributors.
You have to fetch the contributors using GitHub API.

**Comment by Sloth-Panda** [comment]
Can I work on this @rockingrohit9639 ?

**Comment by rockingrohit9639** [comment]
> Can you assign me this @rockingrohit9639 ?

Yeah sure, You can start working on it.
### You are given 5 days to complete this task.

**Comment by Amit366** [comment]
@rockingrohit9639 can I work on this issue??

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 can I work on this issue??

@Amit366 bro, Achyut is already assigned to this issue. If he is not able to do it then you can work on it.

**Comment by rockingrohit9639** [comment]
@Sloth-Panda Remainder !!!

**Comment by rockingrohit9639** [comment]
Sorry @Sloth-Panda Bro, I have to remove you now. Your deadline is over.

**Comment by rockingrohit9639** [comment]
@Amit366 bro, would you like to work on this issue now?

**Comment by Amit366** [comment]
Yes

**Comment by rockingrohit9639** [comment]
> Yes

Ok @Amit366 bro, you can start working on it now.

### You are given 5 days to complete it.

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by rockingrohit9639** [comment]
@Amit366 bro, this is the last reminder for you. Please make your PR.

**Comment by Amit366** [comment]
Sir I will make the PR today itself
