### ISSUE TITLE
Generate password using given text.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#34]
## 💥 Proposal

Generate a password using the given text.
You can include the special keyword in between or the start or at the end.
You can capitalize some alphabets in text. 
No whitespaces should be there.
You can add numbers in the text.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by rockingrohit9639** [comment]
> Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

Yes @Akash20x , you can work on it.
I am assigning you this task. 
If you have any problem while doing it, you can reach me on Discord.

### You are given 5 days to complete this task.

**Comment by Akash20x** [comment]
Ok

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by rockingrohit9639** [comment]
> Please check my pull request

Can you check my comment on your PR?
