### ISSUE TITLE
Host this web app on any free hosting site.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#35]
## 💥 Proposal

Host our project on any free hosting site. 
- Before hosting on the server, make sure our project is working fine. If there is any bug then please let me know.
- You can use Heroku, Netlify, pythonanywhere, or other sites too.
- If you find any issue while doing it, let me know, I will help you.

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by rockingrohit9639** [comment]
> Can i work on this issue

Yes, you can work on it. 
Make sure the project is working fine, before hosting and let me know if there is any issue in the project.
I am assigning you this task.

### You are given 5 days to complete this task.
