### ISSUE TITLE
Updating Homepage and AboutUs page 

### ISSUE THREAD

**Issue by Mansi3546** [rockingrohit9639/TextAnalyzer#38]
Hey..!! @rockingrohit9639 ,.. I want to make home page and about page more attractive ,..using html+css and if you will permit,.. then I would like to add contributor's github id with their name ,.. with some unique way ,.. like on any picture or something like that. so can you please assign this issue to me??..for contribution in CrossWoc.

**Comment by rockingrohit9639** [comment]
> _No description provided._

Yeah @Mansi3546  sure, you can work on it.
If you have any problem while doing it, please let me know.
### You are given 5 days to complete it.

**Comment by rockingrohit9639** [comment]
@Mansi3546 , are you working on this issue?

**Comment by Mansi3546** [comment]
hey @rockingrohit9639 ..as I am working on updating about page and I added contributors with their avtar in the page and some other changes... but when I gone over through the issue#31..it is showing same thing and that issue is not fixed yet.. so should I remove the code that I have written related to -- "add contributors" before making PR ? or you will assign issue#31 to me. .because according to guidelines -- contributor can not make changes in the code until the issue is not assigned to him/her.

**Comment by Akash20x** [comment]
Just a suggestion.. 
@rockingrohit9639 
What I think issue number 31 should be closed as their assignees not be able to solve that issue
And 
@Mansi3546 should complete this issue and updating homepage and add contributors work in this issue itself.

**Comment by rockingrohit9639** [comment]
> hey @rockingrohit9639 ..as I am working on updating about page and I added contributors with their avtar in the page and some other changes... but when I gone over through the issue#31..it is showing same thing and that issue is not fixed yet.. so should I remove the code that I have written related to -- "add contributors" before making PR ? or you will assign issue#31 to me. .because according to guidelines -- contributor can not make changes in the code until the issue is not assigned to him/her.

@Mansi3546 someone is already assigned to that issue. He will make PR today I think, after that you can pull changes and make your changes accordingly. Till then you can work oj homepage or other page's styling.
Thank you.
