### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#4]
Create a landing page that will elaborate on the project.

**Comment by Sloth-Panda** [comment]
As I am working on this I think I can do this too let me know

**Comment by rockingrohit9639** [comment]
@Sloth-Panda Bro, If you now see in the code someone has already added home.html.
So now, you just have to link the pages. Like aboutus page and that index page and update urls.py and views.py
Will you be able to do it?

**Comment by Sloth-Panda** [comment]
sure bro
