### ISSUE TITLE
Search images

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#40]
## 💥 Proposal

Search images using the text given in textarea.

- You can use Unsplash API to search images.
- Create a different page to show all the result images.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a crosswoc

**Comment by rockingrohit9639** [comment]
> Can you please assign me this issue as a crosswoc

Yes @Akash20x , You can work on it.
I am assigning you this issue.
### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
Ok

**Comment by Akash20x** [comment]
Hey I solved it but on sending pull request,
1 check failed for gallery.html, 
This file is created to view images in new page. 
Is there any way to resolve this check 

Or check my file, did I miss something?

**Comment by rockingrohit9639** [comment]
> Hey I solved it but on sending pull request,
> 1 check failed for gallery.html,
> This file is created to view images in new page.
> Is there any way to resolve this check
> 
> Or check my file, did I miss something?

I am reviewing the code.

**Comment by Akash20x** [comment]
Please wait, Again sending the pull request then check

**Comment by rockingrohit9639** [comment]
> lease wait, Again sending the pull req

Ok bro, no problem.
