### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by darklalit14** [rockingrohit9639/TextAnalyzer#42]
Add a button to copy the result to clipboard.

**Comment by arbazalam01** [comment]
can you please assign this to me

**Comment by rockingrohit9639** [comment]
> can you please assign this to me

Yeah @arbazalam01 bro, but first complete another issue. If no one asks for it then I will assign it to you. So that everyone should given a chance.
I hope you understand. Thank you

**Comment by rockingrohit9639** [comment]
@arbazalam01 bro, now you can work on it if you want.
