### ISSUE TITLE
Word meaning

### ISSUE THREAD

**Issue by darklalit14** [rockingrohit9639/TextAnalyzer#43]
Search the meaning of the word written in the text area.

**Comment by Akash20x** [comment]
Please assign this to me as I already solved this type of issue 2 days before, so that I can send a pull request

**Comment by rockingrohit9639** [comment]
> Please assign this to me as I already solved this type of issue 2 days before, so that I can send a pull request

Yes @Akash20x you can work on it.

**Comment by Akash20x** [comment]
Please assign me

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by rockingrohit9639** [comment]
> Please check my pull request

Bro I will review and merge your PR tomorrow. Is it ok for you?

**Comment by Akash20x** [comment]
Okay, No Problem
