### ISSUE TITLE
Suggesting names

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#47]
## 💥 Proposal

Add an option to suggest names on the basis of the word provided in textarea.
E.g. - 
word given - code
output - codder, codegen, thecoder etc.

- You can use API to fetch the suggested names.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a crosswoc

**Comment by rockingrohit9639** [comment]
> Can you please assign me this issue as a crosswoc

Yeah @Akash20x bro, but first complete your another issue. If no one asks for it then I will assign it to you. So that everyone should be given a chance.
I hope you understand. Thank you

**Comment by Akash20x** [comment]
OK

**Comment by Akash20x** [comment]
Hey, now assign me this issue

**Comment by rockingrohit9639** [comment]
> Hey, can you assign me this issue now

Yeah sure, @Akash20x  bro. Now you can work on it.

### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
OK

**Comment by Akash20x** [comment]
Please check my pull request
