### ISSUE TITLE
Highlight the found word

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#48]
## 💥 Proposal

There is a feature in our project to find a particular word in the text, but it only shows found or not found.
Add functionality so that if the word is found then it is highlighted on the output/result page.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Crosswoc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Crosswoc

Ok @Akash20x bro, I am assigning you this issue. 

### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
Hey how can I highlight it in output page
Because it seem something like 1 print statement or any specific thing you want as you mention it as hard.

**Comment by rockingrohit9639** [comment]
@Akash20x bro, can you just make one change. 

You just have to change colour of the found word in the text and keep another text black.

**Comment by Akash20x** [comment]
I tried this but it's not possible
I tried things mention in Internet but nothing worked

**Comment by Akash20x** [comment]
If you know anyway to do this, please tell me approach, I will do it

**Comment by Akash20x** [comment]
`
![IMG_20210228_134517_HHT](https://user-images.githubusercontent.com/46225357/109412020-c7107a80-79cb-11eb-91d6-00fc06b5743d.jpg)
`

**Comment by Akash20x** [comment]
![IMG_20210228_134517_HHT](https://user-images.githubusercontent.com/46225357/109412052-ddb6d180-79cb-11eb-9ea6-ee31205180b2.jpg)

**Comment by rockingrohit9639** [comment]
> I tried to change it's not possible
> I tried things mention in Internet but nothing worked
> 
> Basically what I try was :
> 
> When word is found in string,
> Replace the word with same word of different color
> But the problem is format_html doesn't work with replace and it shows html on result page instead of color change
> 
> Here is where I stuck and didn't find anything relevant in Internet to solve this.

@Akash20x  bro, can you send me a message on discord?

**Comment by Akash20x** [comment]
OK

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by rockingrohit9639** [comment]
> Please check my pull request

I have checked your PR. Good job @Akash20x .
Thank you.
