### ISSUE TITLE
Add a back button

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#49]
## 💥 Proposal

Add a Back button on the result page to navigate the user to the previous or analyze age.

**Comment by Akash20x** [comment]
Hey, I already solved this issue if you can assign me, I will send pull request

**Comment by Akash20x** [comment]
I solve it , please assign me so that I can send a pull request.

**Comment by rockingrohit9639** [comment]
Ok @Akash20x  bro, I am assigning you this issue.

### You have 3 days to complete it.
