### ISSUE TITLE
Create separate pages for analyze and generate 

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#52]
## 💥 Proposal

You have to create separate pages to analyze type of work and generate type of work. 
Like - To Uppercase, Remove Punctuation, To Lower, etc should be on one page while generating a password, find meaning, find images, etc should be on another page. But the functionality should be the same.

I know this can be a difficult task, but don't worry I will always be there to help you. You can send me a message on our Discord server anytime, I will surely reply to you.

You will also be given more time.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of crosswoc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of crosswoc

Ok @Akash20x bro, I am assigning you this issue.
Make sure the functionality remains the same.
Let me know if you have any problems while doing it.

### You are given 8 days to complete it.

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by rockingrohit9639** [comment]
> Please check my pull request

Ok @Akash20x bro.

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Akash20x** [comment]
Final pull request,Check it
