### ISSUE TITLE
Change gallery.html page styling

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#54]
## 💥 Proposal

Show the images something like this - 

![image](https://user-images.githubusercontent.com/40729749/109261346-aad2d900-7825-11eb-9c34-1de8ba7eb358.png)

Also, increase the images fetched.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of crosswoc

**Comment by Akash20x** [comment]
Please assign me this issue as a part of CrossWoc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of CrossWoc

Ok @Akash20x bro, I am assigning you this issue. 

### You are given 4 days to complete it.
