### ISSUE TITLE
Add a navigation bar

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#6]
Add a navigation bar to the project. Link all the pages that are currently in the project.
* Use Bootstrap.

**Comment by Sloth-Panda** [comment]
Can I work on this as part of cwoc?

**Comment by rockingrohit9639** [comment]
> Can I work on this as part of cwoc?

Yes, you can. But make sure if you gave another issue assigned, finish that first.

**Comment by Sloth-Panda** [comment]
@rockingrohit9639  right now I have not been assigned any

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 right now I have not been assigned any

Ok, so I am assigning you this task.

**Comment by rockingrohit9639** [comment]
> > @rockingrohit9639 right now I have not been assigned any
> 
> Ok, so I am assigning you this task.
