### ISSUE TITLE
Add a pre-loader 

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#61]
## 💥 Proposal

Add an awesome pre-loader to the website.

**Comment by pranabprohit** [comment]
Hii @rockingrohit9639, I would like to work on this issue.

**Comment by rockingrohit9639** [comment]
> Hii @rockingrohit9639, I would like to work on this issue.

Yeah @pranabprohit bro, I am assigning you this issue.
Try to get a loader something related to the project, like- a searching, book, text etc.
### Make sure you complete it in 5 days.

**Comment by ayushrastogi689** [comment]
Any update regarding this issue? If no one is working then you can assign it to me.

**Comment by pranabprohit** [comment]
> Any update regarding this issue? If no one is working then you can assign it to me.

I am working on it.

**Comment by rockingrohit9639** [comment]
> > Any update regarding this issue? If no one is working then you can assign it to me.
> 
> I am working on it.

@pranabprohit bro, are you done with it. Because deadline is over.

**Comment by pranabprohit** [comment]
> > > Any update regarding this issue? If no one is working then you can assign it to me.
> > 
> > 
> > I am working on it.
> 
> @pranabprohit bro, are you done with it. Because deadline is over.

Was busy with the exams. I will make the PR today.
