### ISSUE TITLE
Check grammatical mistakes in text provided by user.

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#63]
## 💥 Proposal

Check for all the grammatical mistakes in the text given by the user.
You can use APIs or a Python module to do this task.
If you are not able to find any module or API then reach out to me.
If you have any problem let me know.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Crosswoc

**Comment by arbazalam01** [comment]
Can you please assign this to me

**Comment by rockingrohit9639** [comment]
> Can you please assign this to me

Yes @arbazalam01 bro. You can work on it. I am assigning you this issue. 

### You are given 6 days to complete it.

**Comment by rockingrohit9639** [comment]
@arbazalam01 REMAINDER !!

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

@Akash20x bro, you can work on it now.

### Make sure you complete it in 6 days.

**Comment by Akash20x** [comment]
Please check my pull request
