### ISSUE TITLE
Add a motivational quote

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#64]
## 💥 Proposal

Add a random motivational quote on our landing page. And make it beautiful and attractive. 
The quote can be related to anything.
You can also give a button to change the quote. (Optional)

**Comment by Mansi3546** [comment]
can you please assign this issue to me??
The issue that was assigned to me earlier ... I will make PR of that issue by evening ..

**Comment by rockingrohit9639** [comment]
> can you please assign this issue to me??
> The issue that was assigned to me earlier ... I will make PR of that issue by evening ..

Ok @Mansi3546 , you can work on it.
If you have any problem then let me know.

### You are given 5 days to complete it.

**Comment by Akash20x** [comment]
I want to work on this issue as @Mansi3546 extended the deadline.

**Comment by ayushrastogi689** [comment]
Any update regarding this? If other contributor is not working on this issue I can work on it.

**Comment by rockingrohit9639** [comment]
issue has been fixed
