### ISSUE TITLE
Find links in the text

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#66]
## 💥 Proposal

Search for all the links in the text given by the user and display them in anchor tag on the result page.

**Comment by Blastoise** [comment]
Assign this issue to me.

**Comment by rockingrohit9639** [comment]
> Assign this issue to me.

Yeah, sure @Blastoise bro, you can work on it.
Are you a part of Cross Winter Of Code?

**Comment by Blastoise** [comment]
@rockingrohit9639 Yes

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Yes

Ok @Blastoise

### You are given 4 days to complete it.

**Comment by Blastoise** [comment]
@rockingrohit9639 I think you should add how to run the project because I am running your project in virtual env but getting errors while installing packages from requirements.txt
The error occurs while installing django_heroku which in turn installs psycopg2.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 I think you should add how to run the project because I am running your project in virtual env but getting errors while installing packages from requirements.txt
> The error occurs while installing django_heroku which in turn installs psycopg2.

@Blastoise bro, can you drop me a message on Discord?

**Comment by rockingrohit9639** [comment]
@Blastoise bro, REMAINDER !!!

**Comment by Blastoise** [comment]
Sure it will be done by Today.

**Comment by rockingrohit9639** [comment]
> Sure it will be done by Today.

Ok @Blastoise
