### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#71]
## 💥 Proposal

Add a favicon to our website. 
The favicon should be related to Text.

**Comment by pranabprohit** [comment]
Hii @rockingrohit9639, I would like to work on this issue.

**Comment by rockingrohit9639** [comment]
> Hii @rockingrohit9639, I would like to work on this issue as a part of CWOC.

Yeah sure @pranabprohit bro, You can work on it.

I am assigning you this issue.

### You are given 2 days to complete it.
