### ISSUE TITLE
Add text-wrap

### ISSUE THREAD

**Issue by pri1311** [rockingrohit9639/TextAnalyzer#74]
## 💥 Proposal

In the result section, where the text is displayed, there needs to be text-wrap for the text as it goes out of bounds of normal view.

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by pri1311** [comment]
Please assign this to me

**Comment by rockingrohit9639** [comment]
> Please assign this to me

@pri1311 I have assigned you this issue. 

### You are given 3 days to complete it.
