### ISSUE TITLE
Gallery page showing errors

### ISSUE THREAD

**Issue by pri1311** [rockingrohit9639/TextAnalyzer#78]
**Describe the bug**
----
- When clicked on Results following error displayed on gallery route.

Request Method: | GET
-- | --
https://textanalyzerapp.herokuapp.com/gallery/
3.1.7
NameError
name 'val' is not defined
/app/mysite/views.py, line 51, in gallery
/app/.heroku/python/bin/python
3.9.2
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python39.zip',  '/app/.heroku/python/lib/python3.9',  '/app/.heroku/python/lib/python3.9/lib-dynload',  '/app/.heroku/python/lib/python3.9/site-packages']
Fri, 05 Mar 2021 07:04:58 +0000

**To Reproduce**
----
- Steps to reproduce the behavior:

**Expected behavior**
-----
- Images displayed
- 
**Possible solution**
----
- this happens for a particular search, thus we need to provide error handling and no search results found page or enhance search results as this error arrived on simple search result like 'book'.

**Screenshots**
----
- If applicable, add screenshots to help explain your problem.

**Additional context**
----
- Add any other context about the problem here.You can also mention your system environment in which you are running it.

**Comment by pri1311** [comment]
I am sorry If I forgot to mention, this happens for a particular search, thus we need to provide error handling and no search results found page or enhance search results as this error arrived on simple search result like 'book'.

**Comment by rockingrohit9639** [comment]
> I am sorry If I forgot to mention, this happens for a particular search, thus we need to provide error handling and no search results found page or enhance search results as this error arrived on simple search result like 'book'.

Hi @pri1311 
Thank you for your bug report. 
Would you like to fix this bug?

**Comment by pri1311** [comment]
Hi. I am not very familiar with Django and would hence refrain from making any changes in code file. But I think the solution would be to use some other API like https://serpapi.com/images-results or some other API other than unsplash which would possibly give results for almost all search queries or as I mentioned of no data recieved/images found redirect to a 'no search results found' page.

**Comment by rockingrohit9639** [comment]
> Hi. I am not very familiar with Django and would hence refrain from making any changes in the code file. But I think the solution would be to use some other API like https://serpapi.com/images-results or some other API other than Unsplash which would possibly give results for almost all search queries or as I mentioned, if no data received/images found redirect to a 'no search results found' page.

Thank you for this @pri1311 
Well, I know what the problem is and what could be the solution for it. If you want I can tell you or I will fix this.

**Comment by Akash20x** [comment]
I solved this issue in my update gallery styling issue pull request

If this bug still occuring, please check and tell
