### ISSUE TITLE
Simple spelling and grammatical errors in the website

### ISSUE THREAD

**Issue by pri1311** [rockingrohit9639/TextAnalyzer#79]
## 💥 Proposal

You choosed -> You chose
Adddresses -> Addresses
Minor grammatical changes on About us Page.

### Have you read the *Contributing Guidelines on Pull Requests* ?

Yes

**Comment by pri1311** [comment]
Please assign this issue to me

**Comment by rockingrohit9639** [comment]
> Please assign this issue to me

@pri1311 I have assigned you this issue. And yeah please also correct the mistakes in other pages if found.
