### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#8]
Improve the User Interface of the website.
Redesign input fields, buttons, etc.

**Comment by ShudhanshuSingh** [comment]
Can I work on this as part of cwoc?

**Comment by rockingrohit9639** [comment]
> Can I work on this as part of cwoc?

Yes, you can. I will assign it to you. You can take your time in doing it but try to complete it in 4-5 days.

**Comment by rockingrohit9639** [comment]
@ShudhanshuSingh Remainder.

**Comment by ShudhanshuSingh** [comment]
> @ShudhanshuSingh Remainder.

Ya, I will send it by evening

**Comment by rockingrohit9639** [comment]
@ShudhanshuSingh Ok bro, No problem.
