### ISSUE TITLE
associate link to crosswoc website to its banner

### ISSUE THREAD

**Issue by kmryashasvi** [rockingrohit9639/TextAnalyzer#82]
## 💥 Proposal

I will associate link to crosswoc website to its banner so that, when anyone clicks the crosswoc banner, it will direct them to the website of crosswoc

**Comment by rockingrohit9639** [comment]
> ## 💥 Proposal
> I will associate link to crosswoc website to its banner so that, when anyone clicks the crosswoc banner, it will direct them to the website of crosswoc

Yeah sure @kmryashasvi bro, You can go ahead.

### You are given 3 days to complete it.

**Comment by kmryashasvi** [comment]
> > ## 💥 Proposal
> > I will associate link to crosswoc website to its banner so that, when anyone clicks the crosswoc banner, it will direct them to the website of crosswoc
> 
> Yeah sure @kmryashasvi bro, You can go ahead.
> 
> ### You are given 3 days to complete it.

Its done
