### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by kmryashasvi** [rockingrohit9639/TextAnalyzer#83]
like the one mentioned below 

![image](https://user-images.githubusercontent.com/66861659/110197192-e9911080-7e6f-11eb-9cd7-ea98f42f5687.png)

**Comment by rockingrohit9639** [comment]
> like the one mentioned below
> 
> ![image](https://user-images.githubusercontent.com/66861659/110197192-e9911080-7e6f-11eb-9cd7-ea98f42f5687.png)

Bro this is already done in our repo.
