### ISSUE TITLE
Installation script for Linux users

### ISSUE THREAD

**Issue by Blastoise** [rockingrohit9639/TextAnalyzer#84]
**Is your feature request related to a problem? Please describe.**
requirements.txt is not enough for working with this project locally, so to add a script so that at least Linux users can get started with the project faster.

**Describe the solution you'd like**
Adding a Bash Script that will run and install all the dependencies.

**Describe alternatives you've considered**
Also, we need to add this issue in Contributing.md file so that Windows and macOS can lookup if something goes wrong.

**Comment by rockingrohit9639** [comment]
> **Is your feature request related to a problem? Please describe.**
> requirements.txt is not enough for working with this project locally, so to add a script so that at least Linux users can get started with the project faster.
> 
> **Describe the solution you'd like**
> Adding a Bash Script that will run and install all the dependencies.
> 
> **Describe alternatives you've considered**
> Also, we need to add this issue in Contributing.md file so that Windows and macOS can lookup if something goes wrong.

You can work on it @Blastoise 

### You are given 3 days to complete it.
