### ISSUE TITLE
Update link checkbox option 

### ISSUE THREAD

**Issue by Akash20x** [rockingrohit9639/TextAnalyzer#87]
## 💥 Proposal

Actually the problem is it only tells if input text is link or not and rending to error page on clicking the link. 

Solution :
It would be great if it actually extract the piece of text which have link and open that link webpage. 

Example : 
Input :    texthttps://www.google.com/text
Output : https://www.google.com
Also on click this text open this webpage

Input:
https://github.com/rockingrohit9639/TextAnalyzer/goto
Output : 
https://github.com/rockingrohit9639/TextAnalyzer

**Comment by rockingrohit9639** [comment]
> ## 💥 Proposal
> Actually the problem is it only tells if input text is link or not and rending to error page on clicking the link.
> 
> Solution :
> It would be great if it actually extract the piece of text which have link and open that link webpage.
> 
> Example :
> Input : texthttps://www.google.com/text
> Output : https://www.google.com
> Also on click this text open this webpage
> 
> Input:
> https://github.com/rockingrohit9639/TextAnalyzer/goto
> Output :
> https://github.com/rockingrohit9639/TextAnalyzer

Bro, it is exactly like you said.

**Comment by Akash20x** [comment]
What you mean?

**Comment by Akash20x** [comment]
OK
