### ISSUE TITLE
Convert checkbox to radio-buttons

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#88]
## 💥 Proposal

Convert all the checkboxes to radio-buttons.
Make sure everything is working fine after changing.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

Go ahead @Akash20x 

### You are given 4 days to complete it.
