### ISSUE TITLE
Suggest two or three synonyms or examples for the found text 

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#90]
## 💥 Proposal

Suggest two or three words or examples for a word when the user finds a word in the text.
Examples or synonyms should be of a different colour than that of text and highlighted text.
Show the synonyms below the analyzed text on analyze.html file.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

Ok @Akash20x bro, You can work on it.

### You are given 5 days to complete it.

**Comment by Akash20x** [comment]
In this issue, I have a doubt that first user find the particular word from the text and then give their synonyms or i have to give synonymous of every relevant word in text.

**Comment by Akash20x** [comment]
Hey i have some doubt in this issue, can please write an clear example in comment to understand it better

**Comment by rockingrohit9639** [comment]
@Akash20x sorry, I could now answer your query at that time. Can you tell me now?

**Comment by Akash20x** [comment]
Hey I already figured out that now. 
So don't worry!!

**Comment by rockingrohit9639** [comment]
> Hey I already figured out that now.
> So don't worry!!

Ohh ok @Akash20x that's great.

**Comment by Akash20x** [comment]
Please check my pull request
