### ISSUE TITLE
Suggest books or articles

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#96]
## 💥 Proposal

Suggest some books or articles according to the genre provided by the user.
Give a short description of the book or article and links for those as well.
Keep it on generate page.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

Ok @Akash20x bro, You can work on it. 

### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
Please check my pull request
