### ISSUE TITLE
Suggest YouTube channels

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#97]
## 💥 Proposal

Suggest YouTube channels according to the query provided by the user.
Provide the links for those channels with their logos.
Keep it on a separate page.

E.g. - 
Query = Coding
Channels = Tech With Tim, Code With Harry etc.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by rockingrohit9639** [comment]
> Please assign me this issue as a part of Cross Woc

Ok @Akash20x bro, You can work on it.

### You are given 6 days to complete it.

**Comment by Akash20x** [comment]
Please check my pull request
