### ISSUE TITLE
Improve AboutUs page

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#98]
## 💥 Proposal

Improve AboutUs page.
- Only change the styling.

**Comment by pranabprohit** [comment]
@rockingrohit9639, I would like to work on this issue as a part of CWOC.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639, I would like to work on this issue as a part of CWOC.

You can work on it, @pranabprohit 

### Make sure you complete it in 5 days.

**Comment by rockingrohit9639** [comment]
> > @rockingrohit9639, I would like to work on this issue as a part of CWOC.
> 
> You can work on it, @pranabprohit
> 
> ### Make sure you complete it in 5 days.

@pranabprohit bro, will you do it?

**Comment by pranabprohit** [comment]
> > > @rockingrohit9639, I would like to work on this issue as a part of CWOC.
> > 
> > 
> > You can work on it, @pranabprohit
> > ### Make sure you complete it in 5 days.
> 
> @pranabprohit bro, will you do it?

Yes I will
